language: java

sudo: false

cache:
  directories:
    - $HOME/.m2

before_script:
  - unset GEM_PATH GEM_HOME IRBRC JRUBY_OPTS
  - "export PATH=`pwd`/bin:$PATH"
  - echo $HOME

jdk:
#  - openjdk7
  - oraclejdk8

os:
  - linux

env:
  global:
    - JAVA_OPTS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1"

matrix:
  include:
    # these profile do no need to run for all JDKs
    - env: PHASE='-Pjruby-jars,test -Dinvoker.test=extended'
      jdk: oraclejdk8
  fast_finish: true


branches:
  only:
    - master
    - jruby-1_7
    - /^test-.*$/
    - /^ha-feature/

script: if [[ -v COMMAND ]]; then $COMMAND; else travis_retry mvn -Pbootstrap clean install -Dinvoker.skip=false $PHASE | egrep -v 'Download|\\[exec\\] [[:digit:]]+/[[:digit:]]+|^[[:space:]]*\\[exec\\][[:space:]]*$' ; [ ${PIPESTATUS[0]} == 0 ]; fi
install: /bin/true
notifications:
  irc:
    channels:
      - "irc.freenode.org#jruby"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"

  # update jruby-head installed on Travis CI
  webhooks:
    urls:
      - "https://rubies.travis-ci.org/rebuild/jruby-head"
# we are on a branch
    on_success: always
    on_failure: never
